version: '3.9'

services:
  binance-service:
    image: dzarembo/binance-service:latest
    container_name: binance-service
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8081/actuator/health"]
      interval: 20s
      timeout: 5s
      retries: 5

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 300   # каждые 5 минут
    restart: always
